package com.ewaste.management.service;

import com.ewaste.management.dto.PublicCertificateVerifyDTO;
import com.ewaste.management.dto.RecyclingCertificateDTO;
import com.ewaste.management.entity.DisposalRequest;
import com.ewaste.management.entity.EWasteItem;
import com.ewaste.management.entity.RecyclingCertificate;
import com.ewaste.management.entity.User;
import com.ewaste.management.model.enums.RequestStatus;
import com.ewaste.management.model.enums.UserRole;
import com.ewaste.management.repository.DisposalRequestRepository;
import com.ewaste.management.repository.RecyclingCertificateRepository;
import com.ewaste.management.repository.UserRepository;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.security.access.AccessDeniedException;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.UUID;

@Service
public class CertificateService {

    private final RecyclingCertificateRepository certificateRepository;
    private final DisposalRequestRepository disposalRequestRepository;
    private final UserRepository userRepository;
    private final CertificatePdfGeneratorService pdfGeneratorService;

    @Value("${app.frontend.url:http://localhost:5173}")
    private String frontendBaseUrl;

    private static final String DEFAULT_DISCLAIMER =
            "This digital recycling certificate is generated by the Smart E-Waste Management Platform to verify responsible electronic waste disposal and recycling completion. " +
            "Unless explicitly connected to an officially recognized government recycling authority, this certificate is issued by the application for environmental compliance, tracking, and personal verification purposes. " +
            "It does not constitute a government statutory certificate.";

    public CertificateService(RecyclingCertificateRepository certificateRepository,
                              DisposalRequestRepository disposalRequestRepository,
                              UserRepository userRepository,
                              CertificatePdfGeneratorService pdfGeneratorService) {
        this.certificateRepository = certificateRepository;
        this.disposalRequestRepository = disposalRequestRepository;
        this.userRepository = userRepository;
        this.pdfGeneratorService = pdfGeneratorService;
    }

    @Transactional
    public RecyclingCertificate generateOrGetCertificate(DisposalRequest request) {
        return certificateRepository.findByDisposalRequestId(request.getId())
                .orElseGet(() -> {
                    RecyclingCertificate cert = new RecyclingCertificate();
                    cert.setCertificateNumber("EWC-2026-" + UUID.randomUUID().toString().replace("-", "").substring(0, 8).toUpperCase());
                    cert.setDisposalRequest(request);
                    cert.setIssueDate(LocalDateTime.now());
                    
                    int totalQuantity = request.getItems() != null 
                            ? request.getItems().stream().mapToInt(EWasteItem::getQuantity).sum() 
                            : 1;
                    cert.setTotalWeightKg(BigDecimal.valueOf(totalQuantity * 1.50));
                    cert.setHazardousMaterialsDivertedKg(BigDecimal.valueOf(totalQuantity * 0.35));
                    
                    if (request.getCenter() != null && request.getCenter().getName() != null) {
                        cert.setCertificateUrl(request.getCenter().getName());
                    }
                    
                    return certificateRepository.save(cert);
                });
    }

    @Transactional(readOnly = true)
    public RecyclingCertificateDTO getCertificateById(Long id, String currentUserEmail) {
        RecyclingCertificate cert = certificateRepository.findById(id)
                .orElseThrow(() -> new IllegalArgumentException("Certificate not found with ID: " + id));
        validateAccess(cert.getDisposalRequest(), currentUserEmail);
        return mapToDTO(cert);
    }

    @Transactional
    public RecyclingCertificateDTO getCertificateByRequestId(Long requestId, String currentUserEmail) {
        DisposalRequest request = disposalRequestRepository.findById(requestId)
                .orElseThrow(() -> new IllegalArgumentException("Disposal request not found with ID: " + requestId));

        validateAccess(request, currentUserEmail);

        // Auto-generate if eligible
        RecyclingCertificate cert = generateOrGetCertificate(request);
        return mapToDTO(cert);
    }

    @Transactional
    public byte[] downloadCertificatePdfByRequestId(Long requestId, String currentUserEmail) {
        RecyclingCertificateDTO certDTO = getCertificateByRequestId(requestId, currentUserEmail);
        return pdfGeneratorService.generateCertificatePdf(certDTO);
    }

    @Transactional(readOnly = true)
    public byte[] downloadCertificatePdfById(Long certificateId, String currentUserEmail) {
        RecyclingCertificateDTO certDTO = getCertificateById(certificateId, currentUserEmail);
        return pdfGeneratorService.generateCertificatePdf(certDTO);
    }

    @Transactional(readOnly = true)
    public PublicCertificateVerifyDTO verifyCertificatePublic(String certificateNumber) {
        PublicCertificateVerifyDTO verifyDTO = new PublicCertificateVerifyDTO();
        RecyclingCertificate cert = certificateRepository.findByCertificateNumber(certificateNumber).orElse(null);

        if (cert == null) {
            verifyDTO.setCertificateNumber(certificateNumber);
            verifyDTO.setValid(false);
            verifyDTO.setStatus("NOT_FOUND");
            verifyDTO.setDisclaimer(DEFAULT_DISCLAIMER);
            return verifyDTO;
        }

        DisposalRequest req = cert.getDisposalRequest();

        verifyDTO.setCertificateNumber(cert.getCertificateNumber());
        verifyDTO.setTrackingNumber(req != null ? req.getTrackingNumber() : "N/A");

        if (req != null && req.getItems() != null && !req.getItems().isEmpty()) {
            verifyDTO.setCategory(req.getItems().get(0).getCategory() != null ? req.getItems().get(0).getCategory().name() : "E-Waste");
            verifyDTO.setQuantity(req.getItems().stream().mapToInt(EWasteItem::getQuantity).sum());
        } else {
            verifyDTO.setCategory("Electronic Waste");
            verifyDTO.setQuantity(1);
        }

        verifyDTO.setFinalDisposalMethod(req != null && req.getRecommendedAction() != null 
                ? req.getRecommendedAction().name() : "RECYCLE");
        verifyDTO.setIssueDate(cert.getIssueDate());
        verifyDTO.setRecyclingCenter(req != null && req.getCenter() != null ? req.getCenter().getName() : "Central E-Waste Processing Facility");
        verifyDTO.setStatus(req != null ? req.getStatus().name() : "COMPLETED");
        verifyDTO.setValid(true);
        verifyDTO.setOfficialRecycler(cert.getRecycler() != null && "VERIFIED".equalsIgnoreCase(cert.getRecycler().getVerificationStatus()));
        verifyDTO.setDisclaimer(DEFAULT_DISCLAIMER);

        return verifyDTO;
    }

    private void validateAccess(DisposalRequest request, String currentUserEmail) {
        User currentUser = userRepository.findByEmail(currentUserEmail)
                .orElseThrow(() -> new IllegalArgumentException("User not found: " + currentUserEmail));

        boolean isOwner = request.getUser() != null && request.getUser().getId().equals(currentUser.getId());
        boolean isAuthorizedRole = currentUser.getRole() == UserRole.ADMIN 
                || currentUser.getRole() == UserRole.RECYCLER 
                || currentUser.getRole() == UserRole.COLLECTOR;

        if (!isOwner && !isAuthorizedRole) {
            throw new AccessDeniedException("Access denied: You are not authorized to view this certificate");
        }
    }

    private RecyclingCertificateDTO mapToDTO(RecyclingCertificate cert) {
        RecyclingCertificateDTO dto = new RecyclingCertificateDTO();
        dto.setId(cert.getId());
        dto.setCertificateNumber(cert.getCertificateNumber());
        dto.setIssueDate(cert.getIssueDate());
        dto.setTotalWeightKg(cert.getTotalWeightKg());
        dto.setHazardousMaterialsDivertedKg(cert.getHazardousMaterialsDivertedKg());

        DisposalRequest req = cert.getDisposalRequest();
        if (req != null) {
            dto.setDisposalRequestId(req.getId());
            dto.setTrackingNumber(req.getTrackingNumber());
            dto.setStatus(req.getStatus().name());

            if (req.getUser() != null) {
                dto.setUserName(req.getUser().getFullName());
                dto.setUserEmail(req.getUser().getEmail());
            }

            if (req.getItems() != null && !req.getItems().isEmpty()) {
                dto.setCategory(req.getItems().get(0).getCategory() != null ? req.getItems().get(0).getCategory().name() : "Electronic Waste");
                dto.setQuantity(req.getItems().stream().mapToInt(EWasteItem::getQuantity).sum());
            } else {
                dto.setCategory("Electronic Waste");
                dto.setQuantity(1);
            }

            dto.setFinalDisposalMethod(req.getRecommendedAction() != null ? req.getRecommendedAction().name() : "RECYCLE");
            dto.setRecyclingCenter(req.getCenter() != null ? req.getCenter().getName() : "Central E-Waste Processing Facility");
        }

        if (cert.getRecycler() != null) {
            dto.setRecyclerId(cert.getRecycler().getId());
            dto.setRecyclerCompanyName(cert.getRecycler().getCompanyName());
            dto.setOfficialRecycler("VERIFIED".equalsIgnoreCase(cert.getRecycler().getVerificationStatus()));
        } else {
            dto.setOfficialRecycler(false);
        }

        String verifyUrl = frontendBaseUrl + "/verify-certificate/" + cert.getCertificateNumber();
        dto.setVerificationUrl(verifyUrl);
        dto.setCertificateUrl(verifyUrl);
        dto.setDisclaimer(DEFAULT_DISCLAIMER);

        return dto;
    }
}
